version: "3.8"

services:
  fastapi-service:
    build: .
    container_name: fastapi-solution
    ports:
      - "0.0.0.0:8080:8080"
    restart: unless-stopped
    environment:
      - TZ=UTC
      - TAVILY_API_KEY=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
      - TOGETHER_API_KEY=f1c23b53adacc2b699045900b66cbb88a1f58d882e6c54556a08606b249062e7
    volumes:
      - ./logs:/app/logs
    # Если нужно GPU
    # runtime: nvidia
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [gpu]
